name: clang-format-cn Check
on: workflow_dispatch
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'prov/opx'
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check for C/C++/Protobuf programs (Cornelis Networks-specific).
      uses: jidicula/clang-format-action@v4.10.2
      with:
        clang-format-version: '15'
        check-path: ${{ matrix.path }}
