name: 'Cornelis'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'man/**'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  opx-ci:
    name: OPX CI
    if: github.repository == 'cornelisnetworks/libfabric-internal'
    uses: cornelisnetworks/libfabric-devel/.github/workflows/cn.yml@master
