name: 'Cornelis'

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prechecks:
    name: Prechecks
    if: ${{ github.repository == 'cornelisnetworks/libfabric-internal' }}
    uses: cornelisnetworks/libfabric-devel/.github/workflows/ci-prechecks.yml@master
    secrets:
      CN_OPX_BOT_PAT: ${{ secrets.CN_OPX_BOT_PAT }}
  smoke-test:
    name: Smoke Test
    if:  ${{ github.repository == 'cornelisnetworks/libfabric-internal' }}
    uses: cornelisnetworks/libfabric-devel/.github/workflows/smoke-test.yml@master
    secrets:
      OPXR_ELASTICSEARCH_CREDENTIALS: ${{ secrets.OPXR_ELASTICSEARCH_CREDENTIALS }}
  opa100:
    name: OPA100
    needs: [smoke-test, prechecks]
    if: "${{ github.repository == 'cornelisnetworks/libfabric-internal' && contains(github.event.pull_request.labels.*.name, 'CI: Full Suite') }}"
    uses: cornelisnetworks/libfabric-devel/.github/workflows/ci-opa100.yml@master
    with:
      sha: ${{ github.event.pull_request.head.sha }}
      run-type: "CI"
    secrets:
      OPXR_ELASTICSEARCH_CREDENTIALS: ${{ secrets.OPXR_ELASTICSEARCH_CREDENTIALS }}
  cn5000:
    name: CN5000
    needs: [smoke-test, prechecks]
    if: "${{ github.repository == 'cornelisnetworks/libfabric-internal' && contains(github.event.pull_request.labels.*.name, 'CI: Full Suite') }}"
    uses: cornelisnetworks/libfabric-devel/.github/workflows/ci-cn5000.yml@master
    with:
      sha: ${{ github.event.pull_request.head.sha }}
      run-type: "CI"
    secrets:
      OPXR_ELASTICSEARCH_CREDENTIALS: ${{ secrets.OPXR_ELASTICSEARCH_CREDENTIALS }}
  cleanup:
    name: Clean Up
    needs: [opa100, cn5000]
    if: "${{ github.repository == 'cornelisnetworks/libfabric-internal' && contains(github.event.pull_request.labels.*.name, 'CI: Full Suite') }}"
    uses: cornelisnetworks/libfabric-devel/.github/workflows/ci-cleanup.yml@master
  final-cleanup:
    name: Final Clean Up
    if: "${{ github.repository == 'cornelisnetworks/libfabric-internal' && github.event_name == 'pull_request' && github.event.action == 'closed' }}"
    uses: cornelisnetworks/libfabric-devel/.github/workflows/ci-cleanup.yml@master
